# Generated by Django 4.0.2 on 2022-02-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oganiapp', '0002_category_foodcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда отправлено'),
        ),
    ]
